# Generated by Django 5.1.3 on 2024-12-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productospedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_productos_pedidos', to='app_gral.pedidos'),
        ),
        migrations.AlterField(
            model_name='productosventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_productos_ventas', to='app_gral.ventas'),
        ),
    ]
