# Generated by Django 5.1.3 on 2024-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='CI',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
