# Generated by Django 5.1.3 on 2025-09-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItems',
        ),
    ]
