# Generated by Django 5.1.3 on 2024-11-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0002_rename_items_pedido_productos_en_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='bd_images/', verbose_name='Imagen de perfil'),
        ),
    ]
