# Generated by Django 5.1.3 on 2024-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0002_alter_productospedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
