# Generated by Django 5.1.3 on 2024-12-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0003_alter_ventas_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_productos', to='app_gral.ventas'),
        ),
    ]
