# Generated by Django 5.1.3 on 2024-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0003_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='bd_images/'),
        ),
    ]
