# Generated by Django 5.1.3 on 2024-12-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0004_alter_productosventa_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=10),
        ),
    ]
