# Generated by Django 5.1.3 on 2024-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0005_ventas_is_active_alter_ventas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
