# Generated by Django 5.1.3 on 2024-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0005_alter_ventas_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
