# Generated by Django 5.1.3 on 2024-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0006_pedidos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='monto_adelanto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
