# Generated by Django 5.1.3 on 2024-12-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0006_alter_pedido_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
