# Generated by Django 5.1.3 on 2024-12-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gral', '0008_categoria_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='departamento',
        ),
    ]
